/******************************************************************************/
/* This source, or parts thereof, may be used in any software as long the     */
/* license of NostalgicPlayer is keep. See the LICENSE file for more          */
/* information.                                                               */
/******************************************************************************/
namespace Polycode.NostalgicPlayer.Ports.LibOpenMpt.SoundLib.Containers
{
	/// <summary>
	/// MIDI Continuous Controller Codes
	/// http://home.roadrunner.com/~jgglatt/tech/midispec/ctllist.htm
	/// </summary>
	internal enum MidiCC
	{
		Start = 0,
		BankSelect_Coarse = Start,
		ModulationWheel_Coarse = 1,
		BreathController_Coarse = 2,
		FootPedal_Coarse = 4,
		PortamentoTime_Coarse = 5,
		DataEntry_Coarse = 6,
		Volume_Coarse = 7,
		Balance_Coarse = 8,
		PanPosition_Coarse = 10,
		Expression_Coarse = 11,
		EffectControl1_Coarse = 12,
		EffectControl2_Coarse = 13,
		GeneralPurposeSlider1 = 16,
		GeneralPurposeSlider2 = 17,
		GeneralPurposeSlider3 = 18,
		GeneralPurposeSlider4 = 19,
		BankSelect_Fine = 32,
		ModulationWheel_Fine = 33,
		BreathController_Fine = 34,
		FootPedal_Fine = 36,
		PortamentoTime_Fine = 37,
		DataEntry_Fine = 38,
		Volume_Fine = 39,
		Balance_Fine = 40,
		PanPosition_Fine = 42,
		Expression_Fine = 43,
		EffectControl1_Fine = 44,
		EffectControl2_Fine = 45,
		HoldPedal_OnOff = 64,
		Portamento_OnOff = 65,
		SustenutoPedal_OnOff = 66,
		SoftPedal_OnOff = 67,
		LegatoPedal_OnOff = 68,
		Hold2Pedal_OnOff = 69,
		SoundVariation = 70,
		SoundTimbre = 71,
		SoundReleaseTime = 72,
		SoundAttackTime = 73,
		SoundBrightness = 74,
		SoundControl6 = 75,
		SoundControl7 = 76,
		SoundControl8 = 77,
		SoundControl9 = 78,
		SoundControl10 = 79,
		GeneralPurposeButton1_OnOff = 80,
		GeneralPurposeButton2_OnOff = 81,
		GeneralPurposeButton3_OnOff = 82,
		GeneralPurposeButton4_OnOff = 83,
		EffectsLevel = 91,
		TremoloLevel = 92,
		ChorusLevel = 93,
		CelesteLevel = 94,
		PhaserLevel = 95,
		DataButtonIncrement = 96,
		DataButtonDecrement = 97,
		NonRegisteredParameter_Fine = 98,
		NonRegisteredParameter_Coarse = 99,
		RegisteredParameter_Fine = 100,
		RegisteredParameter_Coarse = 101,
		AllSoundOff = 120,
		AllControllersOff = 121,
		LocalKeyboard_OnOff = 122,
		AllNotesOff = 123,
		OmniModeOff = 124,
		OmniModeOn = 125,
		MonoOperation = 126,
		PolyOperation = 127,
		End = PolyOperation,
	}
}
