<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Polycode.NostalgicPlayer.Ports.Tests.LibFlac.Test</RootNamespace>
    <DocumentationFile>bin\LibFlac.Test.xml</DocumentationFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\NostalgicPlayer.Kit.C\CTypes.cs" Link="CTypes.cs" />
    <Compile Include="..\..\LibFlac\LibFlacTypes.cs" Link="LibFlacTypes.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LibFlac\LibFlac.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\metadata.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
