//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.SidMon20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.SidMon20.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by Thomas Neumann.
        ///
        ///This is a C# version of the original assembly player by Michael Kleps and can play modules in the SidMon 2.0 format..
        /// </summary>
        internal static string IDS_SD2_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_SD2_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Reinier van Vliet.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This is the second version of SidMon. It is not written by the original author, Reinier van Vliet, but instead by Michael Kleps (Unknown/DOC). This time, the player isn&apos;t embedded in the module, but have a real format that is easier to load..
        /// </summary>
        internal static string IDS_SD2_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SD2_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module instrument information.
        /// </summary>
        internal static string IDS_SD2_ERR_LOADING_INSTRUMENTS {
            get {
                return ResourceManager.GetString("IDS_SD2_ERR_LOADING_INSTRUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_SD2_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_SD2_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module sequences.
        /// </summary>
        internal static string IDS_SD2_ERR_LOADING_SEQUENCES {
            get {
                return ResourceManager.GetString("IDS_SD2_ERR_LOADING_SEQUENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module song information.
        /// </summary>
        internal static string IDS_SD2_ERR_LOADING_SONGDATA {
            get {
                return ResourceManager.GetString("IDS_SD2_ERR_LOADING_SONGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module tracks.
        /// </summary>
        internal static string IDS_SD2_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_SD2_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_SD2_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_SD2_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SidMon 2.0.
        /// </summary>
        internal static string IDS_SD2_NAME {
            get {
                return ResourceManager.GetString("IDS_SD2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SidMon 2.0.
        /// </summary>
        internal static string IDS_SD2_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SD2_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
