//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.SoundMon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.SoundMon.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Brian Postma.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This module format have both synthesis and samples and uses 4 voices. Brian have later on created a player on both Windows and Linux, but it&apos;s not his player I use. This is my own conversion, which is more accurate on what to do with the different versions..
        /// </summary>
        internal static string IDS_BP_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Brian Postma.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format have both samples and synthesis sounds, which can be created using drawing tools..
        /// </summary>
        internal static string IDS_BP_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_BP_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Brian Postma.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format have both samples and synthesis sounds, which can be created using drawing tools. This version have more effects that can be applied on the synthesis sounds than the previous version..
        /// </summary>
        internal static string IDS_BP_DESCRIPTION_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_BP_DESCRIPTION_AGENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_BP_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_BP_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module instrument information.
        /// </summary>
        internal static string IDS_BP_ERR_LOADING_INSTINFO {
            get {
                return ResourceManager.GetString("IDS_BP_ERR_LOADING_INSTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_BP_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_BP_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module tracks.
        /// </summary>
        internal static string IDS_BP_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_BP_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song length:.
        /// </summary>
        internal static string IDS_BP_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_BP_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_BP_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_BP_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported / used samples:.
        /// </summary>
        internal static string IDS_BP_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_BP_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used wave tables:.
        /// </summary>
        internal static string IDS_BP_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_BP_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_BP_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_BP_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundMon.
        /// </summary>
        internal static string IDS_BP_NAME {
            get {
                return ResourceManager.GetString("IDS_BP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundMon 1.1.
        /// </summary>
        internal static string IDS_BP_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_BP_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundMon 2.2.
        /// </summary>
        internal static string IDS_BP_NAME_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_BP_NAME_AGENT2", resourceCulture);
            }
        }
    }
}
