//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.SampleConverter.Flac {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.SampleConverter.Flac.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on libFLAC by Xiph.Org Foundation
        ///Converted to C# by Thomas Neumann.
        ///
        ///FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality. This is similar to how Zip works, except with FLAC you will get much better compression because it is designed specifically for audio.
        ///
        ///FLAC stands out as the fastest and most widely supported lossless audio codec, and the only one that at once is non-proprietary, is unen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_FLAC_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_FLAC_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the decoder.
        /// </summary>
        internal static string IDS_FLAC_ERR_DECODER_INITIALIZE_FAILED {
            get {
                return ResourceManager.GetString("IDS_FLAC_ERR_DECODER_INITIALIZE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read meta data.
        /// </summary>
        internal static string IDS_FLAC_ERR_DECODER_READ_METADATA {
            get {
                return ResourceManager.GetString("IDS_FLAC_ERR_DECODER_READ_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the encoder.
        /// </summary>
        internal static string IDS_FLAC_ERR_ENCODER_INITIALIZE_FAILED {
            get {
                return ResourceManager.GetString("IDS_FLAC_ERR_ENCODER_INITIALIZE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not encode sample buffer.
        /// </summary>
        internal static string IDS_FLAC_ERR_ENCODER_WRITE_SAMPLES_FAILED {
            get {
                return ResourceManager.GetString("IDS_FLAC_ERR_ENCODER_WRITE_SAMPLES_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only mono and stereo samples are supported at the moment. You tried to play a sample that uses {0} channels..
        /// </summary>
        internal static string IDS_FLAC_ERR_ILLEGAL_CHANNELS {
            get {
                return ResourceManager.GetString("IDS_FLAC_ERR_ILLEGAL_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track number:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string IDS_FLAC_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_FLAC_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC.
        /// </summary>
        internal static string IDS_FLAC_NAME {
            get {
                return ResourceManager.GetString("IDS_FLAC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC.
        /// </summary>
        internal static string IDS_FLAC_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_FLAC_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string IDS_FLAC_NONE {
            get {
                return ResourceManager.GetString("IDS_FLAC_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_ARTIST {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back cover.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_BACK_COVER {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_BACK_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_BAND {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band logo.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_BAND_LOGO {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_BAND_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_COMPOSER {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_COMPOSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_CONDUCTOR {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_CONDUCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During performance.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_DURING_PERFORMANCE {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_DURING_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During recording.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_DURING_RECORDING {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_DURING_RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File icon.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_FILE_ICON {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_FILE_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_FILE_ICON_STANDARD {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_FILE_ICON_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_FISH {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_FISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front cover.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_FRONT_COVER {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_FRONT_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_ILLUSTRATION {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_ILLUSTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead artist.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_LEAD_ARTIST {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_LEAD_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaflet page.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_LEAFLET_PAGE {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_LEAFLET_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_LYRICIST {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_LYRICIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_MEDIA {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_OTHER {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher logo.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_PUBLISHER_LOGO {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_PUBLISHER_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording location.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_RECORDING_LOCATION {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_RECORDING_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video screen capture.
        /// </summary>
        internal static string IDS_FLAC_PICTURE_TYPE_VIDEO_SCREEN_CAPTURE {
            get {
                return ResourceManager.GetString("IDS_FLAC_PICTURE_TYPE_VIDEO_SCREEN_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string IDS_FLAC_UNKNOWN {
            get {
                return ResourceManager.GetString("IDS_FLAC_UNKNOWN", resourceCulture);
            }
        }
    }
}
