//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.MikMod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.MikMod.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Jean-Paul Mikkers and maintained at the moment by Ozkan Sezer.
        ///Ported to NostalgicPlayer by Thomas Neumann.
        ///
        ///This player can only play NostalgicPlayer UniMod 3.x like modules (only an internal format), but if you have the MikMod converter installed, you will be able to play a lot of different module formats.
        ///
        ///The player is based on MikMod 3.3.11 + what has been added to 3.3.12 so far and my own fixes..
        /// </summary>
        internal static string IDS_MIK_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_MIK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT compressed data is corrupt.
        /// </summary>
        internal static string IDS_MIK_ERR_ITPACKING {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_ITPACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_MIK_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the instrument information.
        /// </summary>
        internal static string IDS_MIK_ERR_LOADING_INSTRUMENTINFO {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_LOADING_INSTRUMENTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_MIK_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample data.
        /// </summary>
        internal static string IDS_MIK_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the track information.
        /// </summary>
        internal static string IDS_MIK_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_MIK_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used patterns:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing pattern:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE7 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE8 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tempo (BPM):.
        /// </summary>
        internal static string IDS_MIK_INFODESCLINE9 {
            get {
                return ResourceManager.GetString("IDS_MIK_INFODESCLINE9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikMod.
        /// </summary>
        internal static string IDS_MIK_NAME {
            get {
                return ResourceManager.GetString("IDS_MIK_NAME", resourceCulture);
            }
        }
    }
}
