//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Client.GuiPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Client.GuiPlayer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_ABOUT_LOGO {
            get {
                object obj = ResourceManager.GetObject("IDB_ABOUT_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_ADD {
            get {
                object obj = ResourceManager.GetObject("IDB_ADD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_AZ {
            get {
                object obj = ResourceManager.GetObject("IDB_AZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_CHECKMARK {
            get {
                object obj = ResourceManager.GetObject("IDB_CHECKMARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_DISK {
            get {
                object obj = ResourceManager.GetObject("IDB_DISK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_EJECT {
            get {
                object obj = ResourceManager.GetObject("IDB_EJECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_FAST_FORWARD {
            get {
                object obj = ResourceManager.GetObject("IDB_FAST_FORWARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_INFORMATION {
            get {
                object obj = ResourceManager.GetObject("IDB_INFORMATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_LIST {
            get {
                object obj = ResourceManager.GetObject("IDB_LIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_LOAD {
            get {
                object obj = ResourceManager.GetObject("IDB_LOAD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_LOOP {
            get {
                object obj = ResourceManager.GetObject("IDB_LOOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_MOVE_DOWN {
            get {
                object obj = ResourceManager.GetObject("IDB_MOVE_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_MOVE_UP {
            get {
                object obj = ResourceManager.GetObject("IDB_MOVE_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_MUTE {
            get {
                object obj = ResourceManager.GetObject("IDB_MUTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_NEXT_MODULE {
            get {
                object obj = ResourceManager.GetObject("IDB_NEXT_MODULE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_NEXT_SONG {
            get {
                object obj = ResourceManager.GetObject("IDB_NEXT_SONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_OPEN {
            get {
                object obj = ResourceManager.GetObject("IDB_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_PAUSE {
            get {
                object obj = ResourceManager.GetObject("IDB_PAUSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_PLAY {
            get {
                object obj = ResourceManager.GetObject("IDB_PLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_PLAYING_ITEM {
            get {
                object obj = ResourceManager.GetObject("IDB_PLAYING_ITEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_PREVIOUS_MODULE {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIOUS_MODULE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_PREVIOUS_SONG {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIOUS_SONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_REMOVE {
            get {
                object obj = ResourceManager.GetObject("IDB_REMOVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_REWIND {
            get {
                object obj = ResourceManager.GetObject("IDB_REWIND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SAMPLE_LOOP {
            get {
                object obj = ResourceManager.GetObject("IDB_SAMPLE_LOOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SAMPLE_PINGPONG {
            get {
                object obj = ResourceManager.GetObject("IDB_SAMPLE_PINGPONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SAMPLES {
            get {
                object obj = ResourceManager.GetObject("IDB_SAMPLES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SAVE {
            get {
                object obj = ResourceManager.GetObject("IDB_SAVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SHUFFLE {
            get {
                object obj = ResourceManager.GetObject("IDB_SHUFFLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SORT {
            get {
                object obj = ResourceManager.GetObject("IDB_SORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SWAP {
            get {
                object obj = ResourceManager.GetObject("IDB_SWAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_ZA {
            get {
                object obj = ResourceManager.GetObject("IDB_ZA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¤L
        ///¤V¤R¤CVersion
        ///
        ///¤B¤CA polycode production (www.nostalgicplayer.dk)
        ///
        ///Credits:
        ///
        ///Main programming: Thomas Neumann
        ///
        ///Documentation: Thomas Neumann
        ///(based on the one written by Jaakko Leikas)
        ///
        ///
        ///
        ///Special thanks to these people:
        ///(See documentation for what)
        ///
        ///¤CPhil Wright
        ///¤CPeter William Wagner
        ///¤CSimon Coghlan
        ///¤CThomas Bolon
        ///¤CDave Gandy
        ///¤CThe MikMod team, specially Miodrag Vallat
        ///¤CAdrien Destugues
        ///¤CRobert Baron
        ///¤CAnd to all you users out there :-)
        ///
        ///
        ///
        ///Features in NostalgicPlayer:
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_ABOUT_TEXT {
            get {
                return ResourceManager.GetString("IDS_ABOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NostalgicPlayer.
        /// </summary>
        internal static string IDS_ABOUT_TITLE {
            get {
                return ResourceManager.GetString("IDS_ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string IDS_AGENTDISPLAY_TITLE {
            get {
                return ResourceManager.GetString("IDS_AGENTDISPLAY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for {0}.
        /// </summary>
        internal static string IDS_AGENTSETTINGS_TITLE {
            get {
                return ResourceManager.GetString("IDS_AGENTSETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string IDS_BUT_OK {
            get {
                return ResourceManager.GetString("IDS_BUT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Skip.
        /// </summary>
        internal static string IDS_BUT_SKIP {
            get {
                return ResourceManager.GetString("IDS_BUT_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip and &amp;remove.
        /// </summary>
        internal static string IDS_BUT_SKIPREMOVE {
            get {
                return ResourceManager.GetString("IDS_BUT_SKIPREMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto&amp;p playing.
        /// </summary>
        internal static string IDS_BUT_STOP {
            get {
                return ResourceManager.GetString("IDS_BUT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append list.
        /// </summary>
        internal static string IDS_DISKMENU_APPEND {
            get {
                return ResourceManager.GetString("IDS_DISKMENU_APPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load list.
        /// </summary>
        internal static string IDS_DISKMENU_LOAD {
            get {
                return ResourceManager.GetString("IDS_DISKMENU_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save list.
        /// </summary>
        internal static string IDS_DISKMENU_SAVE {
            get {
                return ResourceManager.GetString("IDS_DISKMENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent is disabled..
        /// </summary>
        internal static string IDS_ERR_AGENT_DISABLED {
            get {
                return ResourceManager.GetString("IDS_ERR_AGENT_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has been thrown in the program. The program will exit. Error message is:
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("IDS_ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize player.
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_INIT_PLAYER {
            get {
                return ResourceManager.GetString("IDS_ERR_INIT_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the output agent.
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_INITOUTPUTAGENT {
            get {
                return ResourceManager.GetString("IDS_ERR_INITOUTPUTAGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load module.
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_LOAD_FILE {
            get {
                return ResourceManager.GetString("IDS_ERR_LOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the module list. Failed with error:
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_LOAD_LIST {
            get {
                return ResourceManager.GetString("IDS_ERR_LOAD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There doesn&apos;t exist any output agent, so NostalgicPlayer can&apos;t play anything.
        /// </summary>
        internal static string IDS_ERR_NOOUTPUTAGENT {
            get {
                return ResourceManager.GetString("IDS_ERR_NOOUTPUTAGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the sample.
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_SAMPLE_INFO_SAMP_ERRORSAVING {
            get {
                return ResourceManager.GetString("IDS_ERR_SAMPLE_INFO_SAMP_ERRORSAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save a sample with no length..
        /// </summary>
        internal static string IDS_ERR_SAMPLE_INFO_SAMP_NOLENGTH {
            get {
                return ResourceManager.GetString("IDS_ERR_SAMPLE_INFO_SAMP_NOLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only samples can be saved..
        /// </summary>
        internal static string IDS_ERR_SAMPLE_INFO_SAMP_NOTASAMPLE {
            get {
                return ResourceManager.GetString("IDS_ERR_SAMPLE_INFO_SAMP_NOTASAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the module list. Failed with error:
        ///{0}.
        /// </summary>
        internal static string IDS_ERR_SAVE_LIST {
            get {
                return ResourceManager.GetString("IDS_ERR_SAVE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be regonized as a module list..
        /// </summary>
        internal static string IDS_ERR_UNKNOWN_LIST_FORMAT {
            get {
                return ResourceManager.GetString("IDS_ERR_UNKNOWN_LIST_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version ({0}) of a NPML list..
        /// </summary>
        internal static string IDS_ERR_UNKNOWN_LIST_VERSION {
            get {
                return ResourceManager.GetString("IDS_ERR_UNKNOWN_LIST_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To read the documentation, open a browser and
        ///navigate to the official webpage which is:.
        /// </summary>
        internal static string IDS_HELP_MESSAGE {
            get {
                return ResourceManager.GetString("IDS_HELP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string IDS_HELP_TITLE {
            get {
                return ResourceManager.GetString("IDS_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nostalgicplayer.dk.
        /// </summary>
        internal static string IDS_HELP_URL {
            get {
                return ResourceManager.GetString("IDS_HELP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NostalgicPlayer.
        /// </summary>
        internal static string IDS_MAIN_TITLE {
            get {
                return ResourceManager.GetString("IDS_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string IDS_MENU_FILE {
            get {
                return ResourceManager.GetString("IDS_MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string IDS_MENU_FILE_EXIT {
            get {
                return ResourceManager.GetString("IDS_MENU_FILE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open….
        /// </summary>
        internal static string IDS_MENU_FILE_OPEN {
            get {
                return ResourceManager.GetString("IDS_MENU_FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string IDS_MENU_HELP {
            get {
                return ResourceManager.GetString("IDS_MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NostalgicPlayer….
        /// </summary>
        internal static string IDS_MENU_HELP_ABOUT {
            get {
                return ResourceManager.GetString("IDS_MENU_HELP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help….
        /// </summary>
        internal static string IDS_MENU_HELP_HELP {
            get {
                return ResourceManager.GetString("IDS_MENU_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string IDS_MENU_WINDOW {
            get {
                return ResourceManager.GetString("IDS_MENU_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent settings.
        /// </summary>
        internal static string IDS_MENU_WINDOW_AGENT_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_MENU_WINDOW_AGENT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string IDS_MENU_WINDOW_AGENT_SHOW {
            get {
                return ResourceManager.GetString("IDS_MENU_WINDOW_AGENT_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        internal static string IDS_MENU_WINDOW_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_MENU_WINDOW_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IDS_MODULE_INFO_COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string IDS_MODULE_INFO_COLUMN_VALUE {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_COLUMN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active player:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_ACTIVEPLAYER {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_ACTIVEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_AUTHOR {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used channels:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_CHANNELS {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_FILE {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module format:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_MODULEFORMAT {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_MODULEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name / file name:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_MODULENAME {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_MODULENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module size:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_MODULESIZE {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_MODULESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_NA {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time:.
        /// </summary>
        internal static string IDS_MODULE_INFO_ITEM_TIME {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_ITEM_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Information.
        /// </summary>
        internal static string IDS_MODULE_INFO_TITLE {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string IDS_MODULE_INFO_UNKNOWN {
            get {
                return ResourceManager.GetString("IDS_MODULE_INFO_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! A new version of NostalgicPlayer has been
        ///installed. Copy the URL below and insert into a browser to see
        ///what is new..
        /// </summary>
        internal static string IDS_NEWVERSION_MESSAGE {
            get {
                return ResourceManager.GetString("IDS_NEWVERSION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string IDS_NEWVERSION_TITLE {
            get {
                return ResourceManager.GetString("IDS_NEWVERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nostalgicplayer.dk/history.html#{0}.
        /// </summary>
        internal static string IDS_NEWVERSION_URL {
            get {
                return ResourceManager.GetString("IDS_NEWVERSION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None installed.
        /// </summary>
        internal static string IDS_NO_AGENTS {
            get {
                return ResourceManager.GetString("IDS_NO_AGENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: -??:??:??.
        /// </summary>
        internal static string IDS_NONEGATIVETIME {
            get {
                return ResourceManager.GetString("IDS_NONEGATIVETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: ???/??? = ??%.
        /// </summary>
        internal static string IDS_NOPOSITION {
            get {
                return ResourceManager.GetString("IDS_NOPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsongs: ??/??.
        /// </summary>
        internal static string IDS_NOSUBSONGS {
            get {
                return ResourceManager.GetString("IDS_NOSUBSONGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: ??:??:??.
        /// </summary>
        internal static string IDS_NOTIME {
            get {
                return ResourceManager.GetString("IDS_NOTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0:d3}/{1:d3} = {2,2}%.
        /// </summary>
        internal static string IDS_POSITION {
            get {
                return ResourceManager.GetString("IDS_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_INST_COLUMN_NAME {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_INST_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of samples.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_INST_COLUMN_SAMPLENUM {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_INST_COLUMN_SAMPLENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_BITSIZE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_BITSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_INFO {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_LENGTH {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLength.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_LOOPLENGTH {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_LOOPLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LStart.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_LOOPSTART {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_LOOPSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle C.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_MIDDLEC {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_MIDDLEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_NAME {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_PANNING {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_PANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_COLUMN_VOLUME {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_COLUMN_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave: {0}-{1}.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_OCTAVE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_OCTAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_OFF {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_ON {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyphony: {0}.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_POLYPHONY {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_POLYPHONY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_SAVE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save format.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_SAVEFORMAT {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_SAVEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_TYPE_HYBRID {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_TYPE_HYBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_TYPE_SAMPLE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_TYPE_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_SAMP_TYPE_SYNTH {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_SAMP_TYPE_SYNTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_TAB_INSTRUMENT {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_TAB_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_TAB_SAMPLE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_TAB_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument / sample information.
        /// </summary>
        internal static string IDS_SAMPLE_INFO_TITLE {
            get {
                return ResourceManager.GetString("IDS_SAMPLE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string IDS_SELECTMENU_ALL {
            get {
                return ResourceManager.GetString("IDS_SELECTMENU_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string IDS_SELECTMENU_NONE {
            get {
                return ResourceManager.GetString("IDS_SELECTMENU_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_AGENTS_COLUMN_NAME {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_AGENTS_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_AGENTS_COLUMN_VERSION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_AGENTS_COLUMN_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_DESCRIPTION_COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_DESCRIPTION_COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_DISPLAY {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_TAB_FORMATS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_TAB_FORMATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_TAB_OUTPUT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_TAB_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players / converters.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_TAB_PLAYERS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_TAB_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample converters.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_TAB_SAMPLECONVERTERS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_TAB_SAMPLECONVERTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals.
        /// </summary>
        internal static string IDS_SETTINGS_AGENTS_TAB_VISUALS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_AGENTS_TAB_VISUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string IDS_SETTINGS_APPLY {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string IDS_SETTINGS_CANCEL {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_CHANNELS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - 15.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_CHANNELS_0_15 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_CHANNELS_0_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 - 31.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_CHANNELS_16_31 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_CHANNELS_16_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 - 47.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_CHANNELS_32_47 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_CHANNELS_32_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 - 63.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_CHANNELS_48_63 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_CHANNELS_48_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_GENERAL {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate Amiga LED filter.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_GENERAL_AMIGALED {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_GENERAL_AMIGALED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_GENERAL_INTERPOLATION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_GENERAL_INTERPOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo separation.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_GENERAL_STEREOSEPARATION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_GENERAL_STEREOSEPARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap left and right speakers.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_GENERAL_SWAPSPEAKERS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_GENERAL_SWAPSPEAKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer output.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_OUPUT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_OUPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output agent.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_OUPUT_AGENT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_OUPUT_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string IDS_SETTINGS_MIXER_OUPUT_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MIXER_OUPUT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDS_SETTINGS_OK {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to added module.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_ADDJUMP {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_ADDJUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list as default.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_ADDTOLIST {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_ADDTOLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember list on exit.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERLIST {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember playing module.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERLISTPOSITION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERLISTPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember module position.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERMODULEPOSITION {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_REMEMBERMODULEPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan added files.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_SCANFILES {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_SCANFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item number in list.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_SHOWLISTNUMBER {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_SHOWLISTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show module name in titlebar.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_SHOWNAME {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_SHOWNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button tool tips.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_TOOLTIPS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_TOOLTIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use database to store module
        ///information.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_GENERAL_USEDATABASE {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_GENERAL_USEDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double buffering.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_DOUBLEBUFFERING {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_DOUBLEBUFFERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early load.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_EARLYLOAD {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_EARLYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a module error is reached.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error dialog.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SHOW {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip file.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SKIP {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip file and remove from list.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SKIPREMOVE {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_SKIPREMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_STOP {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_LOADING_MODULEERROR_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_PLAYING {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At end of module list.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject module.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_EJECT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_EJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to start.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_JUMPTOSTART {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_JUMPTOSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop module.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_LOOP {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_PLAYING_MODULELISTEND_LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List path.
        /// </summary>
        internal static string IDS_SETTINGS_PATHS_LISTPATH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PATHS_LISTPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module path.
        /// </summary>
        internal static string IDS_SETTINGS_PATHS_MODULEPATH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PATHS_MODULEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scan path.
        /// </summary>
        internal static string IDS_SETTINGS_PATHS_STARTSCANPATH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PATHS_STARTSCANPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        internal static string IDS_SETTINGS_TAB_AGENTS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TAB_AGENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        internal static string IDS_SETTINGS_TAB_MIXER {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TAB_MIXER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string IDS_SETTINGS_TAB_OPTIONS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TAB_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string IDS_SETTINGS_TAB_PATHS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TAB_PATHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string IDS_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string IDS_SORTMENU_SHUFFLE {
            get {
                return ResourceManager.GetString("IDS_SORTMENU_SHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        internal static string IDS_SORTMENU_SORT_AZ {
            get {
                return ResourceManager.GetString("IDS_SORTMENU_SORT_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        internal static string IDS_SORTMENU_SORT_ZA {
            get {
                return ResourceManager.GetString("IDS_SORTMENU_SORT_ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsongs: {0}/{1}.
        /// </summary>
        internal static string IDS_SUBSONGS {
            get {
                return ResourceManager.GetString("IDS_SUBSONGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string IDS_TIME {
            get {
                return ResourceManager.GetString("IDS_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh\:mm\:ss.
        /// </summary>
        internal static string IDS_TIMEFORMAT {
            get {
                return ResourceManager.GetString("IDS_TIMEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d\:hh\:mm\:ss.
        /// </summary>
        internal static string IDS_TIMEFORMAT_BIG {
            get {
                return ResourceManager.GetString("IDS_TIMEFORMAT_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m\:ss.
        /// </summary>
        internal static string IDS_TIMEFORMAT_SMALL {
            get {
                return ResourceManager.GetString("IDS_TIMEFORMAT_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new modules to the list.
        ///The modules will be added in the bottom or
        ///right before the first selected module in the list.
        /// </summary>
        internal static string IDS_TIP_MAIN_ADD {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a pop-up menu where you can read and write the module list to disk.
        /// </summary>
        internal static string IDS_TIP_MAIN_DISK {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_DISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all the selected items one item down.
        ///If you hold down shift while pressing the button,
        ///all the selected modules will be moved to the bottom of the list.
        /// </summary>
        internal static string IDS_TIP_MAIN_DOWN {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing once, ejects the current playing module.
        ///Pressing twice, it will clear the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_EJECT {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_EJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves to the next position.
        ///If on the last position, the next module is loaded instead.
        /// </summary>
        internal static string IDS_TIP_MAIN_FORWARD {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the left mouse button over here to switch between
        ///elapsed and remaining time.
        /// </summary>
        internal static string IDS_TIP_MAIN_INFO {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the module information window.
        /// </summary>
        internal static string IDS_TIP_MAIN_MODULEINFO {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_MODULEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When active, the current playing module will play forever.
        /// </summary>
        internal static string IDS_TIP_MAIN_MODULELOOP {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_MODULELOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute/Unmute the volume.
        /// </summary>
        internal static string IDS_TIP_MAIN_MUTE {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_MUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the next module in the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_NEXTMOD {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_NEXTMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the next subsong.
        /// </summary>
        internal static string IDS_TIP_MAIN_NEXTSONG {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_NEXTSONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/starting the playing module.
        /// </summary>
        internal static string IDS_TIP_MAIN_PAUSE {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds new modules to the module list.
        ///The module list will be cleared before the new modules are added.
        /// </summary>
        internal static string IDS_TIP_MAIN_PLAY {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current position in the playing module.
        ///Press the left mouse button on the rectangle and hold it while
        ///moving the mouse to the left or right to change the position.
        /// </summary>
        internal static string IDS_TIP_MAIN_POSITIONSLIDER {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_POSITIONSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When pressing in the first 2 seconds of a module, the previous module in the list will be loaded.
        ///If you press the button after the first 2 seconds, the module will start over again.
        /// </summary>
        internal static string IDS_TIP_MAIN_PREVMOD {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_PREVMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the previous subsong.
        /// </summary>
        internal static string IDS_TIP_MAIN_PREVSONG {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_PREVSONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected modules from the list.
        /// </summary>
        internal static string IDS_TIP_MAIN_REMOVE {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind to the previous position.
        ///If on first position, the previous module is loaded instead.
        /// </summary>
        internal static string IDS_TIP_MAIN_REWIND {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_REWIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the sample info window where you can see
        ///a lot of information about the samples in the
        ///current playing module.
        /// </summary>
        internal static string IDS_TIP_MAIN_SAMP {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_SAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a pop-up menu where you can do different selections on the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_SELECT {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a pop-up menu, where you can select different things to do on the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_SORT {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will swap two selected modules in the list.
        ///Select the two modules you want to swap and press this button.
        /// </summary>
        internal static string IDS_TIP_MAIN_SWAP {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_SWAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the total time of items selected + the total time in the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_TIME {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the selected number of items + the total number of items in the module list.
        /// </summary>
        internal static string IDS_TIP_MAIN_TOTAL {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all the selected items one item up.
        ///If you hold down shift while pressing the button,
        ///all the selected modules will be moved to the top of the list.
        /// </summary>
        internal static string IDS_TIP_MAIN_UP {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the volume.
        /// </summary>
        internal static string IDS_TIP_MAIN_VOLUME {
            get {
                return ResourceManager.GetString("IDS_TIP_MAIN_VOLUME", resourceCulture);
            }
        }
    }
}
