//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.SampleConverter.AudioIff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.SampleConverter.AudioIff.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NostalgicPlayer sample saver.
        /// </summary>
        internal static string IDS_AUDIOIFF_ANNO {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_ANNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player by Thomas Neumann.
        ///
        ///This is the primary sample file format used on the Machintosh. It&apos;s built on the Electronic Arts IFF file format standard. The samples can contain samples from 1 to 32 bits sample range and as many channels you want.
        ///
        ///This player can play those files (.aiff). It can play samples in any bitrate and frequency, but only mono and stereo samples..
        /// </summary>
        internal static string IDS_AUDIOIFF_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This loader only support mono and stereo samples. You tried to play a sample that uses {0} channels.
        /// </summary>
        internal static string IDS_AUDIOIFF_ERR_ILLEGALCHANNEL {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_ERR_ILLEGALCHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any sound information (COMM chunk) in the file.
        /// </summary>
        internal static string IDS_AUDIOIFF_ERR_NOCOMM {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_ERR_NOCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any sound data chunk (SSND chunk) in the file.
        /// </summary>
        internal static string IDS_AUDIOIFF_ERR_NOSSND {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_ERR_NOSSND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioIFF.
        /// </summary>
        internal static string IDS_AUDIOIFF_NAME {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioIFF.
        /// </summary>
        internal static string IDS_AUDIOIFF_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_AUDIOIFF_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
