//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Visual.PatternViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Visual.PatternViewer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the tracker pattern data in a ProTracker-style grid display..
        /// </summary>
        internal static string IDS_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern viewer visual agent.
        ///Written by Oliver Ickler.
        ///
        ///Display module patterns with real-time playback tracking..
        /// </summary>
        internal static string IDS_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Viewer.
        /// </summary>
        internal static string IDS_NAME {
            get {
                return ResourceManager.GetString("IDS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Viewer.
        /// </summary>
        internal static string IDS_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string IDS_SETTING_BACKGROUND {
            get {
                return ResourceManager.GetString("IDS_SETTING_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current row highlight color.
        /// </summary>
        internal static string IDS_SETTING_CURRENTROW {
            get {
                return ResourceManager.GetString("IDS_SETTING_CURRENTROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow song playback automatically.
        /// </summary>
        internal static string IDS_SETTING_FOLLOWSONG {
            get {
                return ResourceManager.GetString("IDS_SETTING_FOLLOWSONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongPattern display font.
        /// </summary>
        internal static string IDS_SETTING_FONT {
            get {
                return ResourceManager.GetString("IDS_SETTING_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid line color.
        /// </summary>
        internal static string IDS_SETTING_GRID {
            get {
                return ResourceManager.GetString("IDS_SETTING_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing note highlight color.
        /// </summary>
        internal static string IDS_SETTING_PLAYINGNOTE {
            get {
                return ResourceManager.GetString("IDS_SETTING_PLAYINGNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        internal static string IDS_SETTING_TEXT {
            get {
                return ResourceManager.GetString("IDS_SETTING_TEXT", resourceCulture);
            }
        }
    }
}
