//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Ports.LibTfmxAudioDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Ports.LibTfmxAudioDecoder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not play Atari ST TFMX modules.
        /// </summary>
        internal static string IDS_ERR_ATARI {
            get {
                return ResourceManager.GetString("IDS_ERR_ATARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module is corrupt.
        /// </summary>
        internal static string IDS_ERR_CORRUPT {
            get {
                return ResourceManager.GetString("IDS_ERR_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sample data found.
        /// </summary>
        internal static string IDS_ERR_NO_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_ERR_NO_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs could be found.
        /// </summary>
        internal static string IDS_ERR_NO_SUBSONGS {
            get {
                return ResourceManager.GetString("IDS_ERR_NO_SUBSONGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has not been initialized before.
        /// </summary>
        internal static string IDS_ERR_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("IDS_ERR_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown module format.
        /// </summary>
        internal static string IDS_ERR_UNKNOWN_FORMAT {
            get {
                return ResourceManager.GetString("IDS_ERR_UNKNOWN_FORMAT", resourceCulture);
            }
        }
    }
}
