<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Polycode.NostalgicPlayer.Ports.Tests.LibOpenMpt.Test</RootNamespace>
    <DocumentationFile>bin\LibOpenMpt.Test.xml</DocumentationFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\NostalgicPlayer.Kit.C\CTypes.cs" Link="CTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\Common\MptPathTypes.cs" Link="MptPathTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\Common\MptRandomTypes.cs" Link="MptRandomTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\LibOpenMptTypes.cs" Link="LibOpenMptTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\Mpt\Crc\CrcTypes.cs" Link="CrcTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\Mpt\Endian\EndianTypes.cs" Link="EndianTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\Mpt\Random\Default_Engines.cs" Link="Default_Engines.cs" />
    <Compile Include="..\..\LibOpenMpt\SoundBase\MixTypes.cs" Link="MixTypes.cs" />
    <Compile Include="..\..\LibOpenMpt\SoundLib\Snd_Defs_Types.cs" Link="Snd_Defs_Types.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.5.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LibOpenMpt\LibOpenMpt.csproj" />
  </ItemGroup>

</Project>
