//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.DigitalMugician {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.DigitalMugician.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Reinier van Vliet.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play both 4 voices and 7 voices Digital Mugician modules..
        /// </summary>
        internal static string IDS_DMU_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DMU_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Reinier van Vliet.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format is the successor of SidMon. The authors want to improve SidMon to a more mature platform and upgrade it. It can both do synthesis sounds as well as samples..
        /// </summary>
        internal static string IDS_DMU_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DMU_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Reinier van Vliet.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format is a 7 voices version of the first Digital Mugician editor. It was never released to the public. It works by combining 2 sub-songs into one song. The first 3 voices of the first sub-song are played normally, but all the 4 voices of the second sub-song are mixed together. It tooks so much CPU power to do, so even the display may max be in 16 colors to save DMA cycles..
        /// </summary>
        internal static string IDS_DMU_DESCRIPTION_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_DMU_DESCRIPTION_AGENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the arpegio information.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_ARPEGGIOS {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_ARPEGGIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module instrument information.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_INSTRUMENTS {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_INSTRUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module sample information.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module tracks.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module waveforms.
        /// </summary>
        internal static string IDS_DMU_ERR_LOADING_WAVEFORMS {
            get {
                return ResourceManager.GetString("IDS_DMU_ERR_LOADING_WAVEFORMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used wave tables:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_DMU_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_DMU_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Mugician.
        /// </summary>
        internal static string IDS_DMU_NAME {
            get {
                return ResourceManager.GetString("IDS_DMU_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Mugician.
        /// </summary>
        internal static string IDS_DMU_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DMU_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Mugician 2.
        /// </summary>
        internal static string IDS_DMU_NAME_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_DMU_NAME_AGENT2", resourceCulture);
            }
        }
    }
}
