//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.IffSmus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.IffSmus.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Mark Riley.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play IFF-SMUS modules. The instruments need to be stored in a directory called Instruments in the same directory as the song file..
        /// </summary>
        internal static string IDS_SMUS_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_SMUS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Mark Riley.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play IFF-SMUS modules. The instruments need to be stored in a directory called Instruments in the same directory as the song file.
        ///
        ///This format is build on the standard IFF format. SMUS stands for Simple MUsical Score. The format is note based like MIDI files..
        /// </summary>
        internal static string IDS_SMUS_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SMUS_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module instruments.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_INSTRUMENTS {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_INSTRUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the required chunks are missing.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_MISSING_CHUNK {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_MISSING_CHUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open external file with name {0}. Make sure you have an Instruments folder in the same folder as the module, which have all needed instruments.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_OPEN_EXTERNAL_FILE {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_OPEN_EXTERNAL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read external file with name {0}.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_READ_EXTERNAL_FILE {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_READ_EXTERNAL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module tracks.
        /// </summary>
        internal static string IDS_SMUS_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_SMUS_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_SMUS_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_SMUS_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tempo (Hz):.
        /// </summary>
        internal static string IDS_SMUS_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_SMUS_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF-SMUS.
        /// </summary>
        internal static string IDS_SMUS_NAME {
            get {
                return ResourceManager.GetString("IDS_SMUS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF-SMUS.
        /// </summary>
        internal static string IDS_SMUS_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SMUS_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
