//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Output.DiskSaver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Output.DiskSaver.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_OPEN {
            get {
                object obj = ResourceManager.GetObject("IDB_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_SETTINGS {
            get {
                object obj = ResourceManager.GetObject("IDB_SETTINGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string IDS_BUT_NO {
            get {
                return ResourceManager.GetString("IDS_BUT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string IDS_BUT_OK {
            get {
                return ResourceManager.GetString("IDS_BUT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IDS_BUT_YES {
            get {
                return ResourceManager.GetString("IDS_BUT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound output agent which stores the output to disk.
        ///Written by Thomas Neumann.
        ///
        ///This agent will write the sound output as a sample file on your harddisk. The format to save in can be selected between the available converters..
        /// </summary>
        internal static string IDS_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory ({0}) does not exists..
        /// </summary>
        internal static string IDS_ERR_DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_ERR_DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected converter is not loaded or enabled..
        /// </summary>
        internal static string IDS_ERR_NO_CONVERTER {
            get {
                return ResourceManager.GetString("IDS_ERR_NO_CONVERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected pass-through output agent is not loaded or enabled..
        /// </summary>
        internal static string IDS_ERR_NO_OUTPUT {
            get {
                return ResourceManager.GetString("IDS_ERR_NO_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any format to save as..
        /// </summary>
        internal static string IDS_ERR_NO_SELECTED_CONVERTER {
            get {
                return ResourceManager.GetString("IDS_ERR_NO_SELECTED_CONVERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file ({0}) already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string IDS_MSG_OVERWRITE_FILE {
            get {
                return ResourceManager.GetString("IDS_MSG_OVERWRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Saver.
        /// </summary>
        internal static string IDS_NAME {
            get {
                return ResourceManager.GetString("IDS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Saver.
        /// </summary>
        internal static string IDS_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 bit.
        /// </summary>
        internal static string IDS_SETTINGS_16BIT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_16BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 bit.
        /// </summary>
        internal static string IDS_SETTINGS_32BIT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_32BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 bit.
        /// </summary>
        internal static string IDS_SETTINGS_8BIT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_8BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        internal static string IDS_SETTINGS_FORMAT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string IDS_SETTINGS_FREQUENCY {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string IDS_SETTINGS_MONO {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_MONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass through output agent.
        /// </summary>
        internal static string IDS_SETTINGS_PASSTHROUGH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PASSTHROUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string IDS_SETTINGS_PASSTHROUGH_NONE {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PASSTHROUGH_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string IDS_SETTINGS_PATH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string IDS_SETTINGS_STEREO {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_STEREO", resourceCulture);
            }
        }
    }
}
