//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.OpenMpt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.OpenMpt.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Olivier Lapicque and mainly maintained at the moment by Johannes &quot;Saga Musix&quot; Schultz.
        ///Ported to NostalgicPlayer by Thomas Neumann.
        ///
        ///This player uses the LibOpenMpt. It is a continuation of ModPlug Tracker. This player will be used for OpenMPT specific formats or modules using features not supported by LibXmp..
        /// </summary>
        internal static string IDS_MPT_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_MPT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load module
        ///{0}.
        /// </summary>
        internal static string IDS_MPT_ERR_LOADING {
            get {
                return ResourceManager.GetString("IDS_MPT_ERR_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used patterns:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing pattern:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tempo (BPM):.
        /// </summary>
        internal static string IDS_MPT_INFODESCLINE7 {
            get {
                return ResourceManager.GetString("IDS_MPT_INFODESCLINE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenMPT.
        /// </summary>
        internal static string IDS_MPT_NAME {
            get {
                return ResourceManager.GetString("IDS_MPT_NAME", resourceCulture);
            }
        }
    }
}
