//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.DavidWhittaker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.DavidWhittaker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by David Whittaker.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can load all the different versions of David Whittaker players and extract and play the module information from them..
        /// </summary>
        internal static string IDS_DW_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DW_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by David Whittaker.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format is not a standard file format like other modules. The music data are embedded into an assembler player, so the whole module file contains both the player and music. This player can recognize all the different versions of David Whittakers player and extract the data and play them back..
        /// </summary>
        internal static string IDS_DW_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DW_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read module arpeggios.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_ARPEGGIOS {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_ARPEGGIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read module envelopes.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_ENVELOPES {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_ENVELOPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sub-song information.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_SUBSONG {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_SUBSONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read module tracks.
        /// </summary>
        internal static string IDS_DW_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_DW_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song length:.
        /// </summary>
        internal static string IDS_DW_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_DW_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_DW_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_DW_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_DW_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_DW_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_DW_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_DW_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Whittaker.
        /// </summary>
        internal static string IDS_DW_NAME {
            get {
                return ResourceManager.GetString("IDS_DW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Whittaker.
        /// </summary>
        internal static string IDS_DW_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DW_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
