//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.SampleConverter.Iff16Sv {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.SampleConverter.Iff16Sv.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NostalgicPlayer sample saver.
        /// </summary>
        internal static string IDS_IFF16SV_ANNO {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_ANNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format is an extension to the primary sample format (IFF-8SVX) on the Amiga. It contains 16-bit samples instead of 8-bit samples.
        ///
        ///{0}.
        /// </summary>
        internal static string IDS_IFF16SV_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This one supports plain PCM files, which means no compression at all..
        /// </summary>
        internal static string IDS_IFF16SV_DESCRIPTION_PCM {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_DESCRIPTION_PCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any sound data chunk (BODY chunk) in the file.
        /// </summary>
        internal static string IDS_IFF16SV_ERR_NOBODY {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_ERR_NOBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any sound information (VHDR chunk) in the file.
        /// </summary>
        internal static string IDS_IFF16SV_ERR_NOVHDR {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_ERR_NOVHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octaves:.
        /// </summary>
        internal static string IDS_IFF16SV_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        internal static string IDS_IFF16SV_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation:.
        /// </summary>
        internal static string IDS_IFF16SV_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string IDS_IFF16SV_NA {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF-16SV (PCM).
        /// </summary>
        internal static string IDS_IFF16SV_NAME_PCM {
            get {
                return ResourceManager.GetString("IDS_IFF16SV_NAME_PCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF-16SV.
        /// </summary>
        internal static string IDS_NAME {
            get {
                return ResourceManager.GetString("IDS_NAME", resourceCulture);
            }
        }
    }
}
