//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.DigiBoosterPro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.DigiBoosterPro.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Grzegorz Kraszewski.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can load both DigiBooster Pro 2.x and DigiBooster 3 modules. Both uses the format called DBM0.
        ///
        ///The player also support echo effects..
        /// </summary>
        internal static string IDS_DBM_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DBM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Grzegorz Kraszewski.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player plays modules created with DigiBooster Pro 2.x. The editor was created by Tomasz and Waldemar Piasta. It was one of the first editors which was able to play more than 8 channels..
        /// </summary>
        internal static string IDS_DBM_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DBM_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Grzegorz Kraszewski.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player plays modules created with DigiBooster 3.x. This editor was continued by Grzegorz Kraszewski and has been totally rewritten in C. It is available for multiple Amiga OS&apos;es..
        /// </summary>
        internal static string IDS_DBM_DESCRIPTION_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_DBM_DESCRIPTION_AGENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module is corrupted.
        /// </summary>
        internal static string IDS_DBM_ERR_DATA_CORRUPTED {
            get {
                return ResourceManager.GetString("IDS_DBM_ERR_DATA_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading of data failed.
        /// </summary>
        internal static string IDS_DBM_ERR_READING_DATA {
            get {
                return ResourceManager.GetString("IDS_DBM_ERR_READING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit samples not supported.
        /// </summary>
        internal static string IDS_DBM_ERR_SAMPLE_SIZE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("IDS_DBM_ERR_SAMPLE_SIZE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported format version.
        /// </summary>
        internal static string IDS_DBM_ERR_VERSION_UNSUPPORTED {
            get {
                return ResourceManager.GetString("IDS_DBM_ERR_VERSION_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong chunk order in the module.
        /// </summary>
        internal static string IDS_DBM_ERR_WRONG_CHUNK_ORDER {
            get {
                return ResourceManager.GetString("IDS_DBM_ERR_WRONG_CHUNK_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song length:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used patterns:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM:.
        /// </summary>
        internal static string IDS_DBM_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_DBM_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigiBooster Pro.
        /// </summary>
        internal static string IDS_DBM_NAME {
            get {
                return ResourceManager.GetString("IDS_DBM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigiBooster Pro 2.x.
        /// </summary>
        internal static string IDS_DBM_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DBM_NAME_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigiBooster 3.x.
        /// </summary>
        internal static string IDS_DBM_NAME_AGENT2 {
            get {
                return ResourceManager.GetString("IDS_DBM_NAME_AGENT2", resourceCulture);
            }
        }
    }
}
