//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.DeltaMusic20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.DeltaMusic20.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by Thomas Neumann.
        ///
        ///This is a C# version of the original assembly player by Bent Nielsen and can play modules in the Delta Music 2.0 format..
        /// </summary>
        internal static string IDS_DM2_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_DM2_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Bent Nielsen.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This is the second major version of this editor. It has got a totally overhaul on how to create the synthesis instruments..
        /// </summary>
        internal static string IDS_DM2_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DM2_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the arpeggios.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_ARPEGGIOS {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_ARPEGGIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module blocks.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_BLOCK {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the instrument information.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_INSTRUMENT {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample data.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read track data.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the waveform data.
        /// </summary>
        internal static string IDS_DM2_ERR_LOADING_WAVEFORM {
            get {
                return ResourceManager.GetString("IDS_DM2_ERR_LOADING_WAVEFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing positions:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_DM2_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_DM2_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Music 2.0.
        /// </summary>
        internal static string IDS_DM2_NAME {
            get {
                return ResourceManager.GetString("IDS_DM2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Music 2.0.
        /// </summary>
        internal static string IDS_DM2_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_DM2_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
