//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.InStereo20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.InStereo20.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Hans Bergstedt.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play InStereo! version 2.0 modules. It is based on the original assembly player from the Amiga..
        /// </summary>
        internal static string IDS_IS20_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_IS20_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Hans Bergstedt.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This is the precursor of Synthesis and Sonic Arranger. This is a total rewrite of the player since InStereo 1.0. It is a new file format and a few extra features has been added..
        /// </summary>
        internal static string IDS_IS20_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_IS20_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_IS20_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_IS20_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the instrument information.
        /// </summary>
        internal static string IDS_IS20_ERR_LOADING_INSTRUMENT {
            get {
                return ResourceManager.GetString("IDS_IS20_ERR_LOADING_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module sample.
        /// </summary>
        internal static string IDS_IS20_ERR_LOADING_SAMPLE {
            get {
                return ResourceManager.GetString("IDS_IS20_ERR_LOADING_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_IS20_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_IS20_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the track.
        /// </summary>
        internal static string IDS_IS20_ERR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("IDS_IS20_ERR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of track rows:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks from line:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tempo (Hz):.
        /// </summary>
        internal static string IDS_IS20_INFODESCLINE7 {
            get {
                return ResourceManager.GetString("IDS_IS20_INFODESCLINE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStereo! 2.0.
        /// </summary>
        internal static string IDS_IS20_NAME {
            get {
                return ResourceManager.GetString("IDS_IS20_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStereo! 2.0.
        /// </summary>
        internal static string IDS_IS20_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_IS20_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
