//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.VoodooSupremeSynthesizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.VoodooSupremeSynthesizer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Tomas Partl
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play Voodoo Supreme Synthesizer modules..
        /// </summary>
        internal static string IDS_VSS_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_VSS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Tomas Partl
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format use mostly synth sounds with some nice effects like morphing. Can also play samples in a very special way, but it is only used for drums..
        /// </summary>
        internal static string IDS_VSS_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_VSS_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read envelope.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_ENVELOPE {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_ENVELOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read period command table.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_PERIODTABLE {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_PERIODTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read module sample.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_SAMPLE {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read track.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read waveform.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_WAVEFORM {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_WAVEFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read waveform table.
        /// </summary>
        internal static string IDS_VSS_ERR_LOADING_WAVEFORMTABLE {
            get {
                return ResourceManager.GetString("IDS_VSS_ERR_LOADING_WAVEFORMTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_VSS_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_VSS_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_VSS_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_VSS_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used wave tables:.
        /// </summary>
        internal static string IDS_VSS_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_VSS_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voodoo Supreme Synthesizer.
        /// </summary>
        internal static string IDS_VSS_NAME {
            get {
                return ResourceManager.GetString("IDS_VSS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voodoo Supreme Synthesizer.
        /// </summary>
        internal static string IDS_VSS_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_VSS_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
