//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.Oktalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.Oktalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by Thomas Neumann.
        ///
        ///This is a C# version of the original assembly player by Armin Sander and can play modules in the Oktalyzer format..
        /// </summary>
        internal static string IDS_OKT_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_OKT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Armin Sander.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format is one of the first to support multiple channels, which means more than 4 channels, on the Amiga. It support upto 8 channels, but each channels doesn&apos;t have indepent volume control. When you changed the volume on a channel that is mixed together with another one, you change the volume on both channels.
        ///
        ///This player is able to play all Oktalyzer modules with 4 to 8 channels..
        /// </summary>
        internal static string IDS_OKT_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_OKT_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunk ({0}) has an invalid size ({1}).
        /// </summary>
        internal static string IDS_OKT_ERR_INVALID_CHUNK_SIZE {
            get {
                return ResourceManager.GetString("IDS_OKT_ERR_INVALID_CHUNK_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_OKT_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_OKT_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module patterns.
        /// </summary>
        internal static string IDS_OKT_ERR_LOADING_PATTERNS {
            get {
                return ResourceManager.GetString("IDS_OKT_ERR_LOADING_PATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample data.
        /// </summary>
        internal static string IDS_OKT_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_OKT_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown chunk ({0}{1}{2}{3}) has been read.
        /// </summary>
        internal static string IDS_OKT_ERR_UNKNOWN_CHUNK {
            get {
                return ResourceManager.GetString("IDS_OKT_ERR_UNKNOWN_CHUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used patterns:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported / used samples:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing pattern:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_OKT_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_OKT_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktalyzer.
        /// </summary>
        internal static string IDS_OKT_NAME {
            get {
                return ResourceManager.GetString("IDS_OKT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktalyzer.
        /// </summary>
        internal static string IDS_OKT_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_OKT_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
