//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.SidPlaySettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.SidPlaySettings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_OPEN {
            get {
                object obj = ResourceManager.GetObject("IDB_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIA model.
        /// </summary>
        internal static string IDS_SETTINGS_CIA {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS-6526.
        /// </summary>
        internal static string IDS_SETTINGS_CIA_6526 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CIA_6526", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS-6526 from week 44/1985.
        /// </summary>
        internal static string IDS_SETTINGS_CIA_6526_W4485 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CIA_6526_W4485", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS-8521.
        /// </summary>
        internal static string IDS_SETTINGS_CIA_8521 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CIA_8521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock speed.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always play at this speed.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_ALWAYS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_ALWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drean.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_DREAN {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_DREAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when speed is not known.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_NOT_KNOWN {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_NOT_KNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_NTSC {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_NTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old NTSC.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_NTSC_OLD {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_NTSC_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_PAL {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL-M.
        /// </summary>
        internal static string IDS_SETTINGS_CLOCK_PALM {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_CLOCK_PALM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVSC.
        /// </summary>
        internal static string IDS_SETTINGS_HVSC {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_HVSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable bug list.
        /// </summary>
        internal static string IDS_SETTINGS_HVSC_BUGLIST {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_HVSC_BUGLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to HVSC collection.
        /// </summary>
        internal static string IDS_SETTINGS_HVSC_PATH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_HVSC_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable song length database.
        /// </summary>
        internal static string IDS_SETTINGS_HVSC_SONGLENGTH {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_HVSC_SONGLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable STIL.
        /// </summary>
        internal static string IDS_SETTINGS_HVSC_STIL {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_HVSC_STIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost digisounds on MOS-8580.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_DIGIBOOST {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_DIGIBOOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable filter.
        /// </summary>
        internal static string IDS_SETTINGS_OPTIONS_FILTER_ENABLE {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_OPTIONS_FILTER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID model.
        /// </summary>
        internal static string IDS_SETTINGS_SID {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS-6581.
        /// </summary>
        internal static string IDS_SETTINGS_SID_6581 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_SID_6581", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOS-8580.
        /// </summary>
        internal static string IDS_SETTINGS_SID_8580 {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_SID_8580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use this model.
        /// </summary>
        internal static string IDS_SETTINGS_SID_ALWAYS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_SID_ALWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when model is not known.
        /// </summary>
        internal static string IDS_SETTINGS_SID_NOT_KNOWN {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_SID_NOT_KNOWN", resourceCulture);
            }
        }
    }
}
