<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Polycode.NostalgicPlayer.Library.Test</RootNamespace>
    <DocumentationFile>bin\NostalgicPlayer.Library.Test.xml</DocumentationFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NostalgicPlayer.Library\NostalgicPlayer.Library.csproj" />
  </ItemGroup>

</Project>