//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.BenDaglish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.BenDaglish.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Colin Dooley made for Ben Daglish.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can load all the different versions of Ben Daglish players and extract and play the module information from them..
        /// </summary>
        internal static string IDS_BD_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by Colin Dooley made for Ben Daglish.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This format is not a standard file format like other modules. The music data are embedded into an assembler player, so the whole module file contains both the player and music. This player can recognize all the different versions of Ben Daglishs player and extract the data and play them back..
        /// </summary>
        internal static string IDS_BD_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_BD_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read position lists.
        /// </summary>
        internal static string IDS_BD_ERR_LOADING_POSITION_LISTS {
            get {
                return ResourceManager.GetString("IDS_BD_ERR_LOADING_POSITION_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_BD_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_BD_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_BD_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_BD_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sub-song information.
        /// </summary>
        internal static string IDS_BD_ERR_LOADING_SUBSONG {
            get {
                return ResourceManager.GetString("IDS_BD_ERR_LOADING_SUBSONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read module tracks.
        /// </summary>
        internal static string IDS_BD_ERR_LOADING_TRACKS {
            get {
                return ResourceManager.GetString("IDS_BD_ERR_LOADING_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_BD_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_BD_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used tracks:.
        /// </summary>
        internal static string IDS_BD_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_BD_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_BD_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_BD_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing positions:.
        /// </summary>
        internal static string IDS_BD_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_BD_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks:.
        /// </summary>
        internal static string IDS_BD_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_BD_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben Daglish.
        /// </summary>
        internal static string IDS_BD_NAME {
            get {
                return ResourceManager.GetString("IDS_BD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben Daglish.
        /// </summary>
        internal static string IDS_BD_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_BD_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
