//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.FutureComposer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.FutureComposer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by Thomas Neumann.
        ///
        ///This player can only play Future Composer 1.4 modules, but it is also used to play the 1.0 - 1.3 modules, but not directly. The old formats are converted to 1.4 format and then this player is used.
        ///
        ///It is based on the original assembly player from the Amiga, but it contains a lot of bug fixes. Hopefully it can play the modules correctly..
        /// </summary>
        internal static string IDS_FC_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_FC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by SuperSero.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This is the same as Future Composer 1.0 - 1.3, except that it has been improved by having its own wave tables instead of static tables..
        /// </summary>
        internal static string IDS_FC_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_FC_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_FC_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_FC_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module patterns.
        /// </summary>
        internal static string IDS_FC_ERR_LOADING_PATTERNS {
            get {
                return ResourceManager.GetString("IDS_FC_ERR_LOADING_PATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_FC_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_FC_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module samples.
        /// </summary>
        internal static string IDS_FC_ERR_LOADING_SAMPLES {
            get {
                return ResourceManager.GetString("IDS_FC_ERR_LOADING_SAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song length:.
        /// </summary>
        internal static string IDS_FC_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_FC_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used patterns:.
        /// </summary>
        internal static string IDS_FC_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_FC_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported / used samples:.
        /// </summary>
        internal static string IDS_FC_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_FC_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used wave tables:.
        /// </summary>
        internal static string IDS_FC_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_FC_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_FC_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_FC_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Composer.
        /// </summary>
        internal static string IDS_FC_NAME {
            get {
                return ResourceManager.GetString("IDS_FC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Composer 1.4.
        /// </summary>
        internal static string IDS_FC_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_FC_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
