/******************************************************************************/
/* This source, or parts thereof, may be used in any software as long the     */
/* license of NostalgicPlayer is keep. See the LICENSE file for more          */
/* information.                                                               */
/******************************************************************************/
namespace Polycode.NostalgicPlayer.Ports.LibOpenMpt.Containers
{
	/// <summary>
	/// Parameter index to use with get_render_param and set_render_param
	/// </summary>
	public enum Render_Param
	{
		/// <summary>
		/// The related value represents a relative gain in milliBel.
		/// The default value is 0.
		/// The supported value range is unlimited
		/// </summary>
		MasterGain_MilliBel = 1,

		/// <summary>
		/// The related value represents the stereo separation generated by the libopenmpt mixer in percent.
		/// The default value is 100.
		/// The supported value range is [0,200]
		/// </summary>
		StereoSeparation_Percent = 2,

		/// <summary>
		/// The related value represents the interpolation filter length used by the libopenmpt mixer.
		/// The default value is 0, which indicates a recommended default value.
		/// The supported value range is [0,inf). Values greater than the implementation limit are clamped to the maximum supported value.
		/// Currently supported values:
		/// - 0: internal default
		/// - 1: no interpolation (zero order hold)
		/// - 2: linear interpolation
		/// - 4: cubic interpolation
		/// - 8: windowed sinc with 8 taps
		/// </summary>
		InterpolationFilter_Length = 3,

		/// <summary>
		/// The related value represents the amount of volume ramping done by the libopenmpt mixer.
		/// The default value is -1, which indicates a recommended default value.
		/// The meaningful value range is [-1..10].
		/// A value of 0 completely disables volume ramping. This might cause clicks in sound output.
		/// Higher values imply slower/softer volume ramps
		/// </summary>
		VolumeRamping_Strength = 4
	}
}
