//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polycode.NostalgicPlayer.Agent.Player.SonicArranger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polycode.NostalgicPlayer.Agent.Player.SonicArranger.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by BrainTrace Design.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This player can play Sonic Arranger modules. It is based on the original assembly player from the Amiga..
        /// </summary>
        internal static string IDS_SA_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_SA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original player by BrainTrace Design.
        ///Converted to C# by Thomas Neumann.
        ///
        ///This is the successor of InStereo! and Synthesis editors. The file format is the same as InStereo! 2.0, but changed a little bit.
        ///
        ///The synthesis sounds has improved a little bit from what InStereo! 2.0 could do. The special synthesis effects from the Synthesis format has also been incorporated, so you can say, that Sonic Arranger is a fusion between InStereo! 2.0 and Synthesis..
        /// </summary>
        internal static string IDS_SA_DESCRIPTION_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SA_DESCRIPTION_AGENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the ADSR table.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_ADSR {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_ADSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the AMF table.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_AMF {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_AMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module header.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the instrument information.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_INSTRUMENT {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the module sample.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_SAMPLE {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the sample information.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the track.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read the waveform.
        /// </summary>
        internal static string IDS_SA_ERR_LOADING_WAVEFORM {
            get {
                return ResourceManager.GetString("IDS_SA_ERR_LOADING_WAVEFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of positions:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE0 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of track rows:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE1 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used instruments:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE2 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used samples:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE3 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used wave tables:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE4 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing position:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE5 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing tracks from line:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE6 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE7 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tempo (Hz):.
        /// </summary>
        internal static string IDS_SA_INFODESCLINE8 {
            get {
                return ResourceManager.GetString("IDS_SA_INFODESCLINE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic Arranger.
        /// </summary>
        internal static string IDS_SA_NAME {
            get {
                return ResourceManager.GetString("IDS_SA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic Arranger.
        /// </summary>
        internal static string IDS_SA_NAME_AGENT1 {
            get {
                return ResourceManager.GetString("IDS_SA_NAME_AGENT1", resourceCulture);
            }
        }
    }
}
