name: Run unit test for Ancient
on:
  workflow_dispatch:
  push:
    paths:
      - '**/Ancient/**'
      - '**/Ancient.Test/**'

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore Source\NostalgicPlayer.sln
      - name: Build
        run: dotnet build Source\NostalgicPlayer.sln --configuration Debug -p:Platform="Any CPU" --no-restore
      - name: Test
        run: dotnet test Source\Ports\Tests\Ancient.Test\Ancient.Test.csproj --no-build --verbosity normal
